#!/bin/sh
# Regenerates native/bridge/vulkan_trampolines.S from the Vulkan symbols the
# core actually references. Run after a build when a submodule bump adds new
# direct Vulkan calls (the link will fail with undefined vk* symbols if the
# list is stale — rerun this and rebuild).
#
#   sh ci/gen-vk-trampolines.sh [build-dir]
set -eu

BUILD_DIR="${1:-build-android}"
NDK_BIN="$(dirname "$(command -v "${ANDROID_NDK_HOME:-/opt/homebrew/share/android-ndk}/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang")")"
NM="$NDK_BIN/llvm-nm"
OUT="$(dirname "$0")/../native/bridge/vulkan_trampolines.S"

{
    "$NM" -u "$BUILD_DIR/rpcs3/rpcs3/Emu/librpcs3_emu.a" 2>/dev/null
    for o in "$BUILD_DIR"/bridge/CMakeFiles/cellstation.dir/*.o; do
        # Skip our own dispatcher objects so the table doesn't feed itself.
        case "$o" in *vulkan_loader*) continue;; esac
        "$NM" -u "$o" 2>/dev/null
    done
} | grep -oE '^ *U vk[A-Z][A-Za-z0-9]*' | awk '{print $2}' | sort -u > /tmp/vk-syms.$$

{
    echo "// Generated by ci/gen-vk-trampolines.sh — do not edit by hand."
    echo "// One tail-jump per Vulkan symbol the core references directly; the"
    echo "// pointer table is filled by vk_dispatch_init() (vulkan_loader.cpp)"
    echo "// from either the system libvulkan or an adrenotools-hooked loader."
    echo "#if defined(__aarch64__)"
    echo ".text"
    while read -r sym; do
        printf '\n.global %s\n.type %s, %%function\n%s:\n\tadrp x16, :got:%s_dispatch\n\tldr x16, [x16, :got_lo12:%s_dispatch]\n\tldr x16, [x16]\n\tbr x16\n' "$sym" "$sym" "$sym" "$sym" "$sym"
    done < /tmp/vk-syms.$$
    echo
    echo ".data"
    echo ".balign 8"
    while read -r sym; do
        printf '.global %s_dispatch\n%s_dispatch: .quad 0\n' "$sym" "$sym"
    done < /tmp/vk-syms.$$
    echo "#endif"
} > "$OUT"

# Emit the name list for the loader to dlsym.
LIST="$(dirname "$0")/../native/bridge/vulkan_symbols.inc"
{
    echo "// Generated by ci/gen-vk-trampolines.sh — do not edit by hand."
    while read -r sym; do
        printf 'VK_SYMBOL(%s)\n' "$sym"
    done < /tmp/vk-syms.$$
} > "$LIST"

echo "Wrote $(grep -c '^\.global vk' "$OUT") trampolines to $OUT"
rm -f /tmp/vk-syms.$$
